// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

export interface IProjectFields {
  /** thumbnail */
  thumbnail: Asset;

  /** title */
  title: string;

  /** slug */
  slug: string;

  /** description */
  description: string;

  /** demoUrl */
  demoUrl: string;

  /** githubUrl */
  githubUrl?: string | undefined;
}

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'project';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'project';

export type IEntry = IProject;

export type LOCALE_CODE = 'en-US' | 'pl-PL';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
